name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - "main"

jobs:
  build_wheels:
    name: Build wheels on windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        name: Install Python
        with:
          python-version: "3.x"
      - name: Download libdiscid
        shell: powershell
        run: |
          Invoke-WebRequest -Uri http://ftp.musicbrainz.org/pub/musicbrainz/libdiscid/libdiscid-0.7.0-win.zip -OutFile libdiscid-0.7.0.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
          Expand-Archive -LiteralPath libdiscid-0.7.0.zip -DestinationPath libdiscid-dll
      - name: Prepare libdiscid
        run: |
          mv libdiscid-dll/libdiscid-0.7.0-win/Win32/discid.dll .
          mv libdiscid-dll/libdiscid-0.7.0-win/Win32/discid.lib .
          mv libdiscid-dll/libdiscid-0.7.0-win/Win32/discid.exp .
          mv libdiscid-dll/libdiscid-0.7.0-win/include/discid .
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel
      - name: Set Windows ENV
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp311-win32"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path . -w {dest_dir} -v {wheel}"
      - uses: actions/upload-artifact@v7
        with:
          path: dist/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          sudo apt-get install -y libdiscid-dev pkgconf
          python -m pip install --upgrade pip
          pip install setuptools pkgconfig "Cython >= 3.1"
      - name: Build sdist
        run: |
          python setup.py sdist
      - uses: actions/upload-artifact@v7
        with:
          path: dist/*

  publish:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: artifact
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
